name: example
description: "Widgetbook examples to showcase the Golden Test generation"
version: 0.0.1
homepage:
publish_to: 'none'
resolution: workspace

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  widgetbook_golden_test: any
  widgetbook: ^3.20.2
  widgetbook_samples: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: