name: example
description: "Widgetbook examples to showcase the Golden Test generation"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.16.0
  widgetbook_annotation: ^3.7.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  widgetbook_golden_test:
    path: ../
  widgetbook_golden_test_core:
    path: ../../widgetbook_golden_test_core
  flutter_svg: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  widgetbook_generator: ^3.9.0
  build_runner: ^2.4.9


flutter:
  uses-material-design: true
  generate: true
