name: widgetbook_golden_test
description: "Utility for running golden tests on Widgetbook use cases."
version: 0.3.0
repository: https://github.com/lual98/widgetbook_golden_test
homepage: https://github.com/lual98/widgetbook_golden_test/tree/main/packages/widgetbook_golden_test
topics: [test, widgetbook, golden-test]
resolution: workspace

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  widgetbook: ^3.20.2
  widgetbook_golden_test_core: 0.0.1
  flutter_test:
    sdk: flutter

dev_dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^5.0.0
  provider: ^6.1.5+1
  widgetbook_samples: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: false
