name: Code Coverage

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Set up FVM
        run: |
          dart pub global activate fvm

      - name: Install Flutter version via FVM
        run: fvm install

      - name: Install dependencies
        run: fvm flutter pub get

      - name: Set up melos
        run: |
          dart pub global activate melos

      - name: Run tests with coverage
        run: melos test-coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./packages/widgetbook_golden_test/coverage/lcov.info, ./packages/widgetbook_golden_test_core/coverage/lcov.info
          fail_ci_if_error: true