name: Code Coverage

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Flutter version from .fvmrc
        id: fvm-version
        run: echo "version=$(grep '"flutter":' .fvmrc | cut -d '"' -f 4)" >> $GITHUB_OUTPUT

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-version.outputs.version }}

      - name: Install dependencies
        run: flutter pub get

      - name: Set up melos
        run: |
          dart pub global activate melos

      - name: Run tests with coverage
        run: melos test-coverage
        env:
          CI: true

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./packages/widgetbook_golden_test/coverage/lcov.info, ./packages/widgetbook_golden_test_core/coverage/lcov.info
          fail_ci_if_error: true