name: Ensure Formatting

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  ensure-formatting:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Set up FVM
      run: |
        dart pub global activate fvm

    - name: Set up melos
      run: |
        dart pub global activate melos

    - name: Install Flutter version via FVM
      run: fvm install

    - name: Install dependencies
      run: fvm flutter pub get

    - name: Ensure that files are formatted
      run: melos ensure-format