name: Ensure Formatting

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  ensure-formatting:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Get Flutter version from .fvmrc
      id: fvm-version
      run: echo "version=$(grep '"flutter":' .fvmrc | cut -d '"' -f 4)" >> $GITHUB_OUTPUT

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ steps.fvm-version.outputs.version }}

    - name: Set up melos
      run: |
        dart pub global activate melos

    - name: Install dependencies
      run: flutter pub get

    - name: Ensure that files are formatted
      run: melos ensure-format