name: Publish to pub.dev
# Part 2
permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (e.g. 1.2.3)'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for authentication using OIDC
    steps:
      - uses: actions/checkout@v4

      - name: Get Flutter version from .fvmrc
        id: fvm-version
        run: echo "version=$(grep '"flutter":' .fvmrc | cut -d '"' -f 4)" >> $GITHUB_OUTPUT

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-version.outputs.version }}

      - name: Set up melos
        run: dart pub global activate melos

      - name: Bootstrap
        run: melos bootstrap

      - name: Publish to pub.dev
        run: melos publish --no-dry-run --yes

  github_release:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - uses: actions/checkout@v4

      - name: Extract latest changelog sections
        run: |
          chmod +x .github/scripts/extract_latest_changelog.sh
          .github/scripts/extract_latest_changelog.sh

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          body_path: LATEST_CHANGELOG.md