name: Push release
# Part 1
permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (e.g. 1.2.3)'
        required: true

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Flutter version from .fvmrc
        id: fvm-version
        run: echo "version=$(grep '"flutter":' .fvmrc | cut -d '"' -f 4)" >> $GITHUB_OUTPUT

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-version.outputs.version }}

      - name: Set up melos
        run: |
          dart pub global activate melos

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests with coverage
        run: melos test
  push_release:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update version in pubspec.yaml and CHANGELOG.md
        run: |
          version="${{ github.event.inputs.version }}"
          sed -i "s/^version: .*/version: $version/" ./packages/widgetbook_golden_test/pubspec.yaml
          today=$(date +%Y-%m-%d)
          sed -i "0,/## Unreleased/{s/## Unreleased/## $version - $today/}" ./packages/widgetbook_golden_test/CHANGELOG.md

      - name: Commit version bump
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
          git add ./packages/widgetbook_golden_test/pubspec.yaml ./packages/widgetbook_golden_test/CHANGELOG.md
          git commit -m "chore: release ${{ github.event.inputs.version }}"
          git push

      - name: Create tag
        run: |
          git tag ${{ github.event.inputs.version }}
          git push origin ${{ github.event.inputs.version }}
      - name: Trigger publish workflow
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          gh workflow run publish.yml --ref ${{ github.event.inputs.version }} -f version=${{ github.event.inputs.version }}