name: Update Snapshots

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to update snapshots'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch }}

    - name: Get Flutter version from .fvmrc
      id: fvm-version
      run: echo "version=$(grep '"flutter":' .fvmrc | cut -d '"' -f 4)" >> $GITHUB_OUTPUT

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ steps.fvm-version.outputs.version }}

    - name: Set up melos
      run: |
        dart pub global activate melos

    - name: Install dependencies
      run: flutter pub get

    - name: Update golden snapshots
      run: melos update-goldens

    - name: Commit new snapshots
      if: always()
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Automatic snapshot update in branch ${{ github.event.inputs.branch }}"
        branch: ${{ github.event.inputs.branch }}
        file_pattern: '*.png'