name: Update Snapshots

permissions:
  contents: write

on:
  pull_request:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to update snapshots'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch }}

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Set up FVM
      run: |
        dart pub global activate fvm

    - name: Install Flutter version via FVM
      run: fvm install

    - name: Install dependencies
      run: fvm flutter pub get

    - name: Update golden snapshots
      run: fvm flutter test --update-goldens

    - name: Commit new snapshots
      if: always()
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Automatic snapshot update in branch ${{ github.event.inputs.branch }}"
        branch: ${{ github.event.inputs.branch }}
        file_pattern: '*.png'